name: Fetch Jira Issue Keys

on:
  workflow_dispatch:

jobs:
  fetch_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install jira

      - name: Run Jira Fetcher Script
        env:
          JIRA_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}   # Optional if you want to specify a different Jira URL
          JQL_QUERY: |
            project = RHOAIENG AND fixVersion in (RHOAI_2.16.1) AND 
            (labels not in (RHOAI-releases, RHOAI-internal) OR labels is empty) AND 
            component not in (Documentation, TestOps, DevOps, InfraOps)
        run: |
          python jira_fetcher.py
